### ISSUE TITLE
Possibility of re-licensing sample files

### ISSUE THREAD

**Issue by jthielen** [fmaussion/salem-sample-data#1]
The WRF & `geo_em` sample files contained here would be valuable to reuse in continuing the development of xwrf (xref https://github.com/ncar-xdev/xwrf/issues/42 and https://github.com/ncar-xdev/xwrf/pull/14#issuecomment-1028212997). However, the readme for this repository lists its license as GNU GPLv3, which means we can't reuse them (or creating linkages to them) in a permissively licensed (in xwrf's case, Apache) project. Would you be willing to consider re-licensing this repo or those specific files, or should we pursue finding sample/test files elsewhere?

**Comment by fmaussion** [comment]
Yes this is an oversight. Salem has been BSD3 since several years now, I just forgot to do it here. Doing it now.

**Comment by fmaussion** [comment]
OK, they are public domain now.
